### ISSUE TITLE
Logic bug in mdm plugin

### ISSUE THREAD

**Issue by clburlison** [sheagcraig/sheagcraig_sal_plugins#5]
### Issue
Using `profiles -e` is not an accurate method to determine if a machine was enrolled via DEP. This only tells you that the device is DEP enrollable and **might** have been enrolled via one of the supported DEP install methods.

https://github.com/sheagcraig/sheagcraig_sal_plugins/blob/e97b4e18472838eb11e93787d3b5d86613ec7621/mdm_enrollment/scripts/mdm_enrollment.py#L20-L21

### Steps to replicate
You can have a machine that goes through Setup Assistant without a network connection and then the MDM profile installed via `sudo profiles install -path enroll.mobileconfig`. Via the current logic, `profiles -e`, this machine would report as enrolled via DEP however that would be a lie.

### Valid detection method
The only accurate way to determine if a macOS device is DEP Enrolled is to upgrade it to 10.13.4+ and regex for `Enrolled via DEP: Yes`. Based on the code this should only be an additional few lines in the else block. [reference](https://clburlison.com/10.13.4-uamdm/)

### Solutions
I would recommend reporting back no DEP status on machines less than 10.13.4 so admins are aware that the plugin. Or switch from bool to string and return `'Unknown'` on machines less than 10.13.4. Thoughts?

**Comment by sheagcraig** [comment]
I think the "newly" revised DEP plugin + MDM plugin handle this correctly? I need more coffee... @clburlison  You're a treasure. Let me know if I'm imaginging things.

**Comment by clburlison** [comment]
Works for me. Too bad Apple didn't design this to be a proper client-side API.
